version: '3.8'

services:
  notes-service:
    build: ./notes-service
    container_name: notes-service
    ports:
      - "8000:8000"
    depends_on:
      - notes-db
    env_file:
      - ./notes-service/.env

  notes-db:
    image: postgres:15
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - notes_pgdata:/var/lib/postgresql/data
      - ./notes-service/app/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  public-service:
    build: ./public-service
    container_name: public-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  notes_pgdata:
  mongo_data:
